name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libasound2-dev libfluidsynth-dev libsystemd-dev libcmocka-dev clang-format
      - name: Configure
        run: cmake -B build -DENABLE_TESTS=ON
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
      - name: Lint
        run: clang-format --version
      - name: Packaging
        run: cmake --build build --target package || true
